os: Visual Studio 2017
version: 0.1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: .\Build.ps1

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\code-coverage.xml"

artifacts:
  - path: artifacts\*.nupkg

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: i1W6tTJcvjsCBgTrhbjqjyDi3pGWr8mLfn0J5dycmUK5WY6O8MApgPEQEVl1nEEp
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
